name: Build TWRP Moto G56

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Build Tools
      run: |
        sudo apt-get update
        sudo apt-get install -y bc build-essential zip curl python3 git-core gnupg flex bison gperf libsdl1.1-dev libesd0-dev libwxgtk3.0-gtk3-dev squashfs-tools build-essential zip lzop libncurses5-dev zlib1g-dev g++-multilib gcc-multilib lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip lib32readline-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip

    - name: Install Repo Tool
      run: |
        mkdir -p ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        sudo ln -sf ~/bin/repo /usr/bin/repo

    - name: Sync TWRP Sources
      run: |
        mkdir work
        cd work
        git config --global user.name "Angel"
        git config --global user.email "angel@example.com"
        repo init --depth=1 -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-12.1
        repo sync -j$(nproc --all) --force-sync

    - name: Clone Device Tree
      run: |
        cd work
        git clone https://github.com/TheT4ycan/TWRP_for_bogota.git device/motorola/bogota

    - name: Build recovery.img
      run: |
        cd work
        export ALLOW_MISSING_DEPENDENCIES=true
        source build/envsetup.sh
        lunch twrp_bogota-eng
        mka vendorbootimage -j$(nproc --all)

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: TWRP-MotoG56-Bogota
        path: work/out/target/product/bogota/vendor_boot.img
        
